# Generated by Django 3.0.6 on 2020-05-12 17:00

from django.db import migrations


def add_default_type(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AnswerType = apps.get_model("api", "AnswerType")
    default_typies = ['text', 'choise', 'choise_multi']
    for t in default_typies:
        AnswerType.objects.create(type=t).save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_type),
    ]
