# Generated by Django 3.0.6 on 2020-05-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200512_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.ManyToManyField(blank=True, to='api.Question'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
