# Generated by Django 3.0.6 on 2020-05-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200512_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroptions',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answertype',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpollanswer',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpoolquestionanswer',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
