# Generated by Django 3.0.6 on 2020-05-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200512_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPoolQuestionAnswer',
            new_name='UserPollQuestionAnswer',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(blank=True, to='api.AnswerOptions'),
        ),
    ]
